[build]
builder = "NIXPACKS"
buildCommand = "cd umoja-backend && npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "cd umoja-backend && npx prisma migrate deploy && npm run seed:prod && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10